spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_home_decoration?serverTimezone=UTC&characterEncoding=utf-8
    username: cause
    password: 688099
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181

file:
  upload-dir: D:/CODE/smart-home-decoration-platform/images